import Head from "next/head";

import NavBar from "./components/NavBar";
import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen w-screen">
        <main className="max-w-screen-2xl m-auto bg-white">
          <NavBar />

          <main>
            <Header />

            <div className="py-3 px-36 mt-10 flex flex-wrap justify-center">
              <RestaurantCard />
            </div>
          </main>
        </main>
      </main>
    </>
  );
}
